export const BUSINESS_INFO = {
  brand: "HubService",
  legalName: "HubService",
  siteUrl: "https://servicehubmaster.com",
  phoneDisplay: "+38 (067) 105 05 55",
  phoneE164: "+380671050555",
  email: "info@servicehubmaster.com",
  addressLine: "вул. Козацька, 98",
  city: "Горохів",
  country: "Україна",
  postalCode: "45700",
  workingHoursShort: "Пн-Сб: 09:00 - 20:00",
  workingHoursFull: "Пн-Сб: 09:00 - 20:00, Нд: за попереднім записом",
  instagramUrl: "https://www.instagram.com/hubservice",
  facebookUrl: "https://www.facebook.com/hubservice",
  mapsUrl: "https://maps.app.goo.gl/Jpm5GDXnnsxSL3ih9",
} as const;
